name: agriplant
description: Agriculture plant app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  google_fonts: ^5.1.0
  badges: ^3.1.1
  timelines: ^0.1.0
  easy_stepper: ^0.7.3
  google_sign_in: ^6.1.6
  chat_gpt_sdk: ^2.2.5
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  flutter_easyloading: ^3.0.5
  internet_connection_checker: ^1.0.0+1
  retrofit: ^4.0.3
  weather_icons: ^3.0.0
  intl: ^0.18.1
  package_rename: ^1.5.1
  blur: ^3.1.0
  flutter_image_filters: ^0.0.16
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/services/
    
